version: 2.1
jobs:
  adas-python-unittest:
    docker:
      - image: circleci/python:3.9.4
    steps:
      - checkout
      - run:
          name: Run Unittests
          command: |
            python3 -m unittest discover -s test/unit_test/ -p "*.py"

  adas-python-installation:
    docker:
      - image: circleci/python:3.9.4
    steps:
      - checkout
      - run:
          name: Install adas python
          command: |
            pip install . --verbose

            
workflows:
  version: 2
  adas-build:
    jobs:
      - adas-python-unittest
      - adas-python-installation:
          requires:
            - adas-python-unittest
