version: 2.1
jobs:
  adas-python:
    docker:
      - image: circleci/python:3.9.4
    steps:
      - checkout
      - run:
        name: installation
        command: |
          pip install .
      - run:
        name: unit-tests
        command: |
          python3 -m unittest discover -s test/unit_test/ -p "*.py"
